# Generated by Django 4.0.1 on 2022-06-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('BK', 'Black'), ('WE', 'White'), ('RD', 'Red'), ('BE', 'Blue')], default='BK', max_length=2),
        ),
        migrations.AddField(
            model_name='car',
            name='make',
            field=models.CharField(default='fiat', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(default='pupa', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=2000),
        ),
    ]
