# Generated by Django 4.0.5 on 2022-06-24 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_car_vin_alter_car_make_alter_car_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopartCarAuction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_bid', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('buy_now', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('auction_date', models.DateTimeField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.copartcar')),
            ],
        ),
        migrations.DeleteModel(
            name='CarAuction',
        ),
        migrations.AddConstraint(
            model_name='copartcarauction',
            constraint=models.UniqueConstraint(fields=('car', 'auction_date'), name='Uniqe car and auction date'),
        ),
    ]
